language: node_js

node_js:
  - "6.10.0"

script:
  - echo "Deploying!"

branches:
  only:
    - master

install:
  - npm install -g firebase-tools
  - npm install

after_success:
  - firebase deploy --project bcf-test-58aad --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
    - jonathon@stardotbmp.com
    on_success: always # default: change
    on_failure: always # default: always